module.exports = {
  NEW_CHANNEL_MESSAGE: "NEW_MESSAGE_CHANNEL",
  NEW_CHANNEL_CREATED: "NEW_CHANNEL",
  NEW_MESSAGE_DIRECT: "NEW_MESSAGE_DIRECT",
  USER_BANNED_CHANNEL: "USER_BANNED_CHANNEL",
  USER_TYPING: "USER_TYPING"
};
